### PR TITLE
Stripe var added to SBAccount + Removed camera unused var + Follow/Unfollow

### PR DESCRIPTION
**Pull request by mglagola**

### CODE REVIEW

**Comment by joshholat** [comment]
:+1:

**Comment by JRHeaton** [comment]
Couple of things:
1. When will we not have the full `SBAccount` to pass through to these methods? Most of our other methods take the models themselves.
2. Does the response include new models to deserialize?

**Comment by joshholat** [comment]
The following response returns the user and account objects keyed to `user` and `account`. So no, models already exist.

Regarding having the full object, I guess it's just nice to not have to have that object if you don't need the whole thing. We're only using the one property from it anyways.

**Comment by JRHeaton** [comment]
> @joshholat  [...] So no, models already exist.

There may be models in memory already, but it doesn't mean we shouldn't still be feeding back the latest data to the subscriber of the signal. And it would be completely wacky to have just one signal out of the entire framework break the convention of sending `next`s of deserialized models from the response.

If a subscriber of the signal doesn't need that data, they should simply subscribe to the `complete` and `error` events.

**Comment by joshholat** [comment]
@JRHeaton I meant that `user` and `account` models already exist for #2 of your questions. So they do need to be deserialized, but the methods to do so should already exist.

Regarding what we pass, let's just do whatever keeps things consistent at this point. Fetching an account object isn't that hard and theoretically it would already be stored on disk somewhere or something.

**Comment by mglagola** [comment]
@JRHeaton @joshholat Either way we should chose one, b/c i know there are other methods in which SBAccount/SBSomeModel are being passed. At our current state i think it makes more sense to pass in the object b/c this pattern is used almost everywhere else.

**Pull request merged**
